### ISSUE TITLE
Seperate component from app

### ISSUE THREAD

**Issue by mayurhyphenOs** [hyphenOs/webshark-frontend#33]
It should be ready to be published as package/library

**Comment by mayurhyphenOs** [comment]
Approach:

1. Create a publishable library/package of the component

- Move the component code in `src/lib`. Entrypoint will be `src/lib/index.js` which exports the component
- Setup babel for transpilation of  `src/lib` alone (this way we can use App as demo in the package itself and any code outside `src/lib` will not be available in package) 
-  In `package.json` set `main` entry to `dist/index` (which will be transpiled code of `src/lib/index.js`)

2. Use component library as package

  1. Install as local dependency
     - add "packettrail-ui" "file:<path-to-component-package> in `dependencies` field of projects `package.json`
     - `packettrail-ui` will point to code from `dist/index` (transpiled code) of package's local path

**Comment by gabhijit** [comment]
This approach makes sense and is quite easier to implement. However, I see a potential small problem - 

1. Our App and Component should have separate set of dependencies - and separate `package.json` files. Otherwise it will be confusing what is needed by `App.js` and what is needed by our `lib/*`. So As a quick step above approach is fine. But once we make it work, it's a good idea to separate the two repositories and thus two separate `package.json` files.
